"""empty message

Revision ID: 1b74c5f98b7b
Revises: e8143b47223d
Create Date: 2024-09-30 15:38:57.236857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b74c5f98b7b'
down_revision = 'e8143b47223d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bankcarty',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.Column('monobank', sa.String(length=20), nullable=True),
    sa.Column('privatbank', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bankcarty', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bankcarty_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bankcarty', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bankcarty_id'))

    op.drop_table('bankcarty')
    # ### end Alembic commands ###
