"""empty message

Revision ID: 236bfa8bd22f
Revises: 8666b99866ef
Create Date: 2024-03-14 08:24:45.603832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '236bfa8bd22f'
down_revision = '8666b99866ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('teacher_prize', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.drop_column('teacher_prize')

    # ### end Alembic commands ###
