"""empty message

Revision ID: 4c108c3ad770
Revises: 05046e0f8464
Create Date: 2024-03-10 06:54:46.290513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c108c3ad770'
down_revision = '05046e0f8464'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cource', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cource', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
