"""empty message

Revision ID: 592e67023629
Revises: 1b74c5f98b7b
Create Date: 2024-09-30 16:55:57.766555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '592e67023629'
down_revision = '1b74c5f98b7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bankcarty', schema=None) as batch_op:
        batch_op.add_column(sa.Column('number', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('name_bank', sa.String(length=20), nullable=True))
        batch_op.drop_column('monobank')
        batch_op.drop_column('privatbank')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bankcarty', schema=None) as batch_op:
        batch_op.add_column(sa.Column('privatbank', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('monobank', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.drop_column('name_bank')
        batch_op.drop_column('number')

    # ### end Alembic commands ###
