"""empty message

Revision ID: 8666b99866ef
Revises: 9f54c2113907
Create Date: 2024-03-11 08:29:15.145840

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8666b99866ef'
down_revision = '9f54c2113907'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('datetimes', sa.DateTime(), nullable=True))
        batch_op.drop_column('datetime')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('datetime', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.drop_column('datetimes')

    # ### end Alembic commands ###
