"""empty message

Revision ID: 8b7e37f31d7a
Revises: 6f80a36c1b65
Create Date: 2024-10-07 00:38:24.340080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b7e37f31d7a'
down_revision = '6f80a36c1b65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cashflows', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lessons', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cashflows', schema=None) as batch_op:
        batch_op.drop_column('lessons')

    # ### end Alembic commands ###
