"""empty message

Revision ID: 97bde790a0ce
Revises: 
Create Date: 2024-08-20 13:30:51.127149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97bde790a0ce'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('role', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_id'), ['id'], unique=False)

    op.create_table('info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.Column('country', sa.String(length=150), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('speed', sa.String(length=120), nullable=True),
    sa.Column('value', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('pay_already', sa.Integer(), nullable=True),
    sa.Column('pass_lesson', sa.Integer(), nullable=True),
    sa.Column('finish_lesson', sa.Integer(), nullable=True),
    sa.Column('was_pay_for_lesson', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('info', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_info_id'), ['id'], unique=False)

    op.create_table('cource',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('to_student', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['to_student'], ['info.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cource', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cource_id'), ['id'], unique=False)

    op.create_table('graficks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.Column('weekday', sa.Integer(), nullable=True),
    sa.Column('hour', sa.Integer(), nullable=True),
    sa.Column('minute', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_user'], ['info.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('graficks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_graficks_id'), ['id'], unique=False)

    op.create_table('lessons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teacher', sa.Integer(), nullable=True),
    sa.Column('student', sa.Integer(), nullable=True),
    sa.Column('prize', sa.Integer(), nullable=True),
    sa.Column('teacher_prize', sa.Integer(), nullable=True),
    sa.Column('datetimes', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['student'], ['info.id'], ),
    sa.ForeignKeyConstraint(['teacher'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lessons_id'), ['id'], unique=False)

    op.create_table('teacher_to_student',
    sa.Column('id_Teacher', sa.Integer(), nullable=False),
    sa.Column('id_Student', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_Student'], ['info.id'], ),
    sa.ForeignKeyConstraint(['id_Teacher'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id_Teacher', 'id_Student')
    )
    op.create_table('partcourses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_course', sa.Integer(), nullable=True),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('rypma', sa.DateTime(), nullable=True),
    sa.Column('repetition', sa.DateTime(), nullable=True),
    sa.Column('reading', sa.DateTime(), nullable=True),
    sa.Column('speaking', sa.DateTime(), nullable=True),
    sa.Column('qetion', sa.DateTime(), nullable=True),
    sa.Column('topics', sa.DateTime(), nullable=True),
    sa.Column('associations', sa.DateTime(), nullable=True),
    sa.Column('grammar', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_course'], ['cource.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('partcourses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_partcourses_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('partcourses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_partcourses_id'))

    op.drop_table('partcourses')
    op.drop_table('teacher_to_student')
    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lessons_id'))

    op.drop_table('lessons')
    with op.batch_alter_table('graficks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_graficks_id'))

    op.drop_table('graficks')
    with op.batch_alter_table('cource', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cource_id'))

    op.drop_table('cource')
    with op.batch_alter_table('info', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_info_id'))

    op.drop_table('info')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_id'))

    op.drop_table('user')
    # ### end Alembic commands ###
