"""empty message

Revision ID: a4115c826251
Revises: e85c7a63cf53
Create Date: 2024-01-26 05:46:42.708870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4115c826251'
down_revision = 'e85c7a63cf53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lessons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teacher', sa.Integer(), nullable=True),
    sa.Column('student', sa.Integer(), nullable=True),
    sa.Column('prize', sa.Integer(), nullable=True),
    sa.Column('datetime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['student'], ['info.id'], ),
    sa.ForeignKeyConstraint(['teacher'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lessons_id'), ['id'], unique=False)

    op.create_table('teacher_to_student',
    sa.Column('id_Teacher', sa.Integer(), nullable=False),
    sa.Column('id_Student', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_Student'], ['info.id'], ),
    sa.ForeignKeyConstraint(['id_Teacher'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id_Teacher', 'id_Student')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('teacher_to_student')
    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lessons_id'))

    op.drop_table('lessons')
    # ### end Alembic commands ###
