"""empty message

Revision ID: db90c5ca852a
Revises: 7283c7a5f184
Create Date: 2024-02-13 16:35:03.774329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db90c5ca852a'
down_revision = '7283c7a5f184'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('graficks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('minute', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('graficks', schema=None) as batch_op:
        batch_op.drop_column('minute')

    # ### end Alembic commands ###
