"""empty message

Revision ID: e1f8c888af64
Revises: 
Create Date: 2024-10-16 07:19:17.219923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1f8c888af64'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('graficks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_Teacher', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['id_Teacher'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('graficks', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('id_Teacher')

    # ### end Alembic commands ###
